- src/Resources/esp_idf_example.json
- src/Resources/esp_idf_schema.json
Files esp_idf_example.json and esp_idf_schema.json were expanded of users targets choice.
> Example of json expanded of users targets choice

- .github/workflows/test-offline-installer-dispatch.yml
- .github/workflows/test-online-installer-dispatch.yml
- .github/workflows/test-online-installer-scheduled.yml
- Build-Installer.ps1
- src/InnoSetup/IdfToolsSetup.iss
- src/InnoSetup/PostInstall.iss
> tools: add Windows Terminal dropdown menu registration for ESP-IDF

- Build-Installer.ps1
Closes #32 
New version of idf-env downloads new version of the driver.
> tools: update version of idf-env

- Build-Installer.ps1
Add autocrlf to Offline archive of the repository.
Closes #52 
@JurajSadel PTAL
> tools: add autocrlf to archive with ESP-IDF for Offline installation

- src/InnoSetup/IdfToolsSetup.iss
> bugfix: enable selection of download mirror

- Build-Installer.ps1
- src/InnoSetup/IdfToolsSetup.iss
- src/InnoSetup/Languages/IdfToolsSetup_cs-CZ.isl
- src/InnoSetup/Languages/IdfToolsSetup_en-US.isl
- src/InnoSetup/Languages/IdfToolsSetup_es-ES.isl
- src/InnoSetup/Languages/IdfToolsSetup_pt-BR.isl
- src/InnoSetup/Languages/IdfToolsSetup_pt-PT.isl
- src/InnoSetup/Languages/IdfToolsSetup_sk-SK.isl
- src/InnoSetup/Languages/IdfToolsSetup_zh-CN.isl
- src/InnoSetup/PostInstall.iss
- src/InnoSetup/PreInstall.iss
- src/InnoSetup/Summary.iss
> tools: add Toit Jaguar installation

- Build-Installer.ps1
- README.md
- src/InnoSetup/Eclipse.iss
- src/InnoSetup/IdfToolsSetup.iss
- src/InnoSetup/PostInstall.iss
- src/Resources/download/index.html
* espressif-ide: release 2.4.1
> espressif-ide: Bump version to 2.4.1 (#114)

- Build-Installer.ps1
- README.md
- src/InnoSetup/Eclipse.iss
- src/InnoSetup/IdfToolsSetup.iss
- src/InnoSetup/Pages/IdfPage.iss
- src/InnoSetup/PostInstall.iss
- src/Resources/download/index.html
Release 2.14.
Closes #115 
Closes #117
> Test/release 2.14

- .github/workflows/update-index.yml
- Build-Installer.ps1
- src/InnoSetup/IdfToolsSetup.iss
- src/InnoSetup/Languages/IdfToolsSetup_cs-CZ.isl
- src/InnoSetup/Languages/IdfToolsSetup_en-US.isl
- src/InnoSetup/Languages/IdfToolsSetup_es-ES.isl
- src/InnoSetup/Languages/IdfToolsSetup_pt-BR.isl
- src/InnoSetup/Languages/IdfToolsSetup_pt-PT.isl
- src/InnoSetup/Languages/IdfToolsSetup_sk-SK.isl
- src/InnoSetup/Languages/IdfToolsSetup_zh-CN.isl
- src/InnoSetup/PostInstall.iss
- src/InnoSetup/PreInstall.iss
- src/InnoSetup/Utils.iss
> tools: fix installation of jdk11.0.14_10

- src/InnoSetup/IdfToolsSetup.iss
- src/InnoSetup/Pages/IdfPage.iss
Closes #128 
Addech check to validate Tools path.
> tools: ESP-IDF Tools directory does not support whitepsaces

- src/InnoSetup/IdfToolsSetup.iss
- src/InnoSetup/PostInstall.iss
Closes #131
Closes #113
Installation of drivers component without any other component.
> tools: allow installation of drivers without rest of the stack

- .github/workflows/build-espressif-ide-installer.yml
- Build-Installer.ps1
- README.md
- src/InnoSetup/IdfToolsSetup.iss
- src/Resources/download/index.html
> tools: update to JDK17

- Build-Installer.ps1
- README.md
- src/Resources/download/index.html
Fix constraint file for ESP-IDF 5.0.1
> Bugfix/esp idf 5.0.1 constraint

- Build-Installer.ps1
- src/InnoSetup/Environment.iss
- src/InnoSetup/IdfToolsSetup.iss
- src/InnoSetup/Pages/SystemCheckPage.iss
- src/InnoSetup/PreInstall.iss
- src/InnoSetup/Summary.iss
Switch to Python 3.11 and git 2.39.2
> Feature/python 3.11

- Build-Installer.ps1
- README.md
- src/InnoSetup/IdfToolsSetup.iss
- src/Resources/download/index.html
- src/Resources/download/releases.json
> Release 2.23

- src/Resources/download/index.html
Deleted patch version 4.4.5 from index to left only 4.4.6.
> docs(index): Deleted patch offline version from index.html

- README.md
- src/Resources/download/index.html
- src/Resources/download/releases.json
Added offline installer of ESP-IDF 5.1.2 and offline IDE 2.11.1 with 5.1.2 IDF.
> docs: release offline-5.1.2 and ide-2.11.1 with 5.1.2 idf

- README.md
- src/InnoSetup/IdfToolsSetup.iss
- src/Resources/download/index.html
- src/Resources/download/releases.json
- Updated Git for Windows version
- Added sources description for installation choose (`release version` -  archive download and `release branch` - git clone)
> Release online installer 2.24

- README.md
- scripts/docs_update_release.py
- README update about automatic index.html workflow trigger
- Edited docs_update script to avoid errors when IDF version is not specified for online installer
> docs: Added mention about automatic index.html update

- src/Resources/download/index.html
- The last change with the links will propagate as soon as the workflow will run
- to fix the links now index.html has to be updated manually
> fix(index): Updated links to propagade with workflow

- .github/workflows/build-installer.yml
- scripts/docs_update_release.py
- ESP-IDF v4.4 offline installer drop since the support period has ended
> Dropped IDF v4.4 since it is not supported anymore

- .github/workflows/build-espressif-ide-installer.yml
- .github/workflows/build-installer.yml
* Fixed upload job PATH for the IDE installer
* Failed job - https://github.com/espressif/idf-installer/actions/runs/11699536930/job/32581723667
Tested with this job - https://github.com/espressif/idf-installer/actions/runs/11702440594
> ci: Fix of IDE installer upload PATH

- Build-Installer.ps1
- src/InnoSetup/IdfToolsSetup.iss
Replace generated pdf documentation with html documentation.
> Replace pdf doc with html doc.

- .github/workflows/build-installer.yml
- .github/workflows/build-offline-installer.yml
- Build-Installer.ps1
- Added fixes for the workflow file
- Removed `--only-binary=":all:"` argument when using pip, because wheels which does not have a binary will fail to install (e.g., esptool) https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-only-binary
We are using Espressif's PyPI, so many wheels should be used from here, and the ones that are not available will be built on the runner
---
Before submitting a Pull Request, please ensure the following:
> Build workflow fixes

- .github/workflows/build-installer.yml
---
Before submitting a Pull Request, please ensure the following:
> fix: Fixed version of the yml file
