espressif/idf-installer

Build-Installer.ps1, src/InnoSetup/IdfToolsSetup.iss, src/InnoSetup/PreInstall.iss
Added checkbox for option to install Espressif driver for ESP32-C3 JTAG support.
=> tools: add support for Espressif driver

.github/workflows/build-offline-installer.yml, .github/workflows/build-online-installer.yml
@georgik There is a modification of the workflow to upload releases to dl.espressif.com
At the moment job uploads all releases, including betas, if you think it's better to upload only stable revisions, I can change this.
BTW, do you have any toolkit to update https://dl.espressif.com/dl/esp-idf/ ?
Mahna-Mahna
=> Upload installer to dl.espressif.com

.github/workflows/build-offline-installer.yml, .github/workflows/build-online-installer.yml
With `--no-progress` flag errors are still printed but verbose output of uploading progress is hidden
=> Hide extra logs during upload to s3

src/InnoSetup/IdfToolsSetup.iss, src/InnoSetup/Languages/IdfToolsSetup_en-US.islu, src/InnoSetup/Pages/IdfDownloadPage.iss, src/InnoSetup/Pages/IdfPage.iss
Too long path causes problem in CCache which causes issues like: https://esp32.com/viewtopic.php?f=25&p=67838&sid=d3c6aafbf9c52edf255e1d97273c1de8#p67838
=> tools: display error in case of ESP-IDF path longer than 90 characters

Build-Installer.ps1, src/Batch/idf_cmd_init.bat, src/InnoSetup/Configuration.iss, src/InnoSetup/IdfToolsSetup.iss, src/InnoSetup/PostInstall.iss, src/PowerShell/Initialize-Idf.ps1
Add support for launching ESP-IDF from different working directory.
It's based on esp-idf ID which is generated during installation. Instead of referencing by PATH it's referenced by the ID.
This allows to specify Working directory in LNK files.
The update contains correction for PowerShell, CMD and Windows Terminal Fragments.
The solution should be backward compatible.
Closes #31 #29
=> tools: support for launching ESP-IDF from different directory

Build-Installer.ps1, src/InnoSetup/IdfToolsSetup.iss, src/InnoSetup/Pages/SystemCheckPage.iss
PowerShell command is not available on all OSes. Use Rust implementation in idf-env to retrieve URL which is later on used by Python.
Closes: #5 
Mention: #50 
@JurajSadel PTAL
=> Use idf-env to update system certificates instead of PowerShell

Build-Installer.ps1, README.md, src/InnoSetup/IdfToolsSetup.iss, src/Resources/download/index.html
Prepare windows installer for espressif-ide v2.6.0 with esp-idf v4.4.2
=> ci: Update builds with espressif-ide v2.6.0 and esp-idf v4.4.2

Build-Installer.ps1, README.md, src/InnoSetup/Configuration.iss, src/InnoSetup/Environment.iss, src/InnoSetup/Pages/IdfDownloadPage.iss, src/InnoSetup/Pages/IdfPage.iss
=> tools: add option to disable path check

src/Batch/idf_cmd_init.bat, src/PowerShell/Initialize-Idf.ps1
We already have aliases for esptool.py and espefuse.py, but were missing one for espsecure.py.
Same change will be applied in export.bat, export.ps1 in IDF.
Reported in https://esp32.com/viewtopic.php?t=30260.
=> export: add an alias for espsecure.py

README.md, src/InnoSetup/Configuration.iss, src/InnoSetup/Environment.iss, src/InnoSetup/IdfToolsSetup.iss, src/Resources/download/index.html
- fix problem with backslash in `idf-env.json`
- fix problem with offline installation of gdb in 5.0
- closes https://github.com/espressif/esp-idf/issues/10409
=> Bugfix/forwardslash and offline-5.0

.github/workflows/build-espressif-ide-installer.yml, .github/workflows/build-offline-installer.yml, .github/workflows/build-online-installer-dispatch.yml, .github/workflows/build-online-installer.yml, .github/workflows/test-offline-installer-dispatch.yml, .github/workflows/test-online-installer-dispatch.yml, .github/workflows/test-online-installer-scheduled.yml, .github/workflows/update-index.yml, README.md, src/InnoSetup/IdfToolsSetup.iss, src/Resources/download/index.html
Generate installers for[ Espressif-IDE v2.9.1](https://github.com/espressif/idf-eclipse-plugin/releases/tag/v2.9.1) with ESP-IDF 5.0.1
=> Generate installers for Espressif-IDE v2.9.1 with ESP-IDF 5.0.1

src/InnoSetup/Configuration.iss
IDF installer is building the esp_idf.json file with missing double quotes
=> IEP-1054: Offline installer missing quotes

src/InnoSetup/IdfToolsSetup.iss, src/InnoSetup/Summary.iss
- Changed all occurrences of git version in installer
- New full Git for Windows version from https://git-scm.com/download is used
- The automatic workflow can be used in future to download and upload Git for Windows on Espressif's download server (`bundle-git.yml`) and also create an release
- Action for acquiring minigit `update-idf-git` can be suspended because it is basically duplicate of `bundle-git.yml` but with minigit version
=> feature: Changed all installer git versions

Build-Installer.ps1
IDF Installer is not possible to build because of 
> ambiguous parameter name 'O' 
in the `Invoke-WebRequest` function. [Here is the failed build](https://github.com/espressif/idf-installer/actions/runs/8061393369/job/22019073286) which should be fixed by this change. The build has successfully passed locally.
=> fix: Changed parameter -O to -OutFile for Invoke-WebRequest function

.github/workflows/build-installer.yml, scripts/docs_update_release.py
- Installer choice input fix
- IDF version doesn't need to be specified for online installer type
=> fix: Fixed running called worflow only for chosen installer type

src/InnoSetup/Pages/IdfPage.iss
- When user presents IDF Tools PATH with spaces the error message is shown but the installation process proceeds to the next page with the PATH with spaces
- This fix won't allow the installation process to continue if the PATH of IDF tools contains spaces
Internal tracker: IDF-9702
=> Fix: IDF tools PATH was updated to be not allowed to pass with spaces

src/InnoSetup/IdfToolsSetup.iss
Added to uninstallation of ESP-IDF:
- Whole IDF directory (including frameworks directory, constraints files, ...)
- Start menu icons
- Desktop shortcuts
----------
- GH issue: https://github.com/espressif/esp-idf/issues/13657
=> fix: Uninstallation of whole ESP-IDF

.github/workflows/build-espressif-ide-installer.yml, .github/workflows/build-offline-installer.yml, src/Resources/templates/template_index.html
Based on the reported issue, the fix for the older IDF Installer releases in [Espressif's download server](https://dl.espressif.com/dl/esp-idf/) is provided.
* Fixed automatic tag and asset name generation to correspond with the links
* Changed the tag and asset names already released to make the links work
* Closes https://github.com/espressif/idf-installer/issues/254
=> fix: Fixed links for older releases of Installer

Build-Installer.ps1, src/InnoSetup/IdfToolsSetup.iss, src/InnoSetup/PostInstall.iss
The offline Installer was using the component manager feature to download all the components in the build process and then in the installation process in completely offline mode the components were added.
However, this feature is not fully supported and is causing a few issues so the feature was suspended for now.
=> remove: Removed component registry

Build-Installer.ps1
The `PrepareIdfDriver` function was not checked and the build could pass even with the driver download/extract failure - this leads to the failure of the installation process with this installer build.
* internal tracker - IDF-10959
=> feat(build): Added check for PrepareIdfDriver function

Build-Installer.ps1, scripts/docs_update_release.py, src/InnoSetup/IdfToolsSetup.iss, src/InnoSetup/Languages/IdfToolsSetup_cs-CZ.isl, src/InnoSetup/Languages/IdfToolsSetup_en-US.isl, src/InnoSetup/Languages/IdfToolsSetup_es-ES.isl, src/InnoSetup/Languages/IdfToolsSetup_pt-BR.isl, src/InnoSetup/Languages/IdfToolsSetup_pt-PT.isl, src/InnoSetup/Languages/IdfToolsSetup_sk-SK.isl, src/InnoSetup/Languages/IdfToolsSetup_zh-CN.isl, src/InnoSetup/Pages/SystemCheckPage.iss, src/InnoSetup/PostInstall.iss
- Fixed Action for installer build - the IDE installer type
- Added OS version check and note for the users
- Added option to open the documentation after completed installation
- online installer opens the ESP-IDF website
- offline installer has the ESP-IDF documentation bundled and opens the PDF
- Added successful installation check
- Fixes unwanted opening of the `system` directory if the installation fails
- Updated IDF-ENV version because of the migration of the drivers to our server
--- 
- Internal tracker  for the IDE installer fix: IDF-10094
- Installer improvements internal tracker: IDF-10040
=> Installer improvements

Build-Installer.ps1
* The URL for the PDF download was fixed to be dynamically generated for the branches
Failing build: https://github.com/espressif/idf-installer/actions/runs/11214102858
Fixed build: https://github.com/espressif/idf-installer/actions/runs/11214781512/job/31170576041
=> fix: Fixed offline documentation download URL

Build-Installer.ps1, src/InnoSetup/Environment.iss
esp-clang made part of offline installer required for the Eclipse
Before submitting a Pull Request, please ensure the following:
=> fix(esp_clang): fixed the clang to be installed as part of offline installer

.github/workflows/build-espressif-ide-installer.yml, src/Resources/download/index.html
* Updated IDE Installer URL for the Espressif server to correspond with the download page and the other installers
* Adjusted GH release creation to not be draft and pre-release
It would be better to manage the executable name generation in the scope of the calling workflow, but this would probably require passing artifacts. Since this installer is in the "feature freeze" state, this is the low-effort solution.
* Job with the bad URL: https://github.com/espressif/idf-installer/actions/runs/11214781512/job/31170576041
=> fix: IDE Installer asset name uploaded on server

src/InnoSetup/Environment.iss
Resolving the issue reported on the ESP forum
There was a fix targeting IDE Installer but the online installer had this issue still preserved. This fix should cover all the cases.
* added installation of the esp-clang
* Internal tracker - IDF-11476
* IDE installer PR - https://github.com/espressif/idf-installer/pull/284
* issue on forum - https://esp32.com/viewtopic.php?f=40&t=42286
* tested with the online installer and IDF v5.3.1
=> IDE Installer fix - idf_tools.py was not installing esp-clang

src/InnoSetup/Environment.iss, src/InnoSetup/PreInstall.iss
When the selected IDF branch is the `release` one, perform `git clone` instead of downloading a `zip` archive and `fast-forwarding` to the latest commit
* based on the Mattermost discussion (mention in tracker)
* internal tracker: IDF-10228
----
* online IDF Installer (GitHub, Gitee and JihuLab mirrors)
- release branch (zip archive correctly NOT downloaded -> git clone performed)
- master branch  (zip archive correctly NOT downloaded -> git clone performed)
- released IDF version  (zip archive correctly downloaded)
* offline IDF Installer (working as usual without any issues)
=> fix(environment): Clone IDF release branches instead of downloading zip and then fastforward

src/InnoSetup/Environment.iss
Some submodules' submodules of ESP-IDF  use absolute paths from Github, which causes users to access Github at clone time even if they choose jihulab mirror. To allow users who do not have access to Github to complete the clone, this PR redirected these submodules to jihulab. the idea inspired by https://jihulab.com/esp-mirror/espressif/esp-jihu-tools @wujiangang
* Test passed on Windows11
* The complete log can be found in [Setup Log 2024-06-26 #007.txt](https://github.com/user-attachments/files/17917174/Setup.Log.2024-06-26.007.txt)
* The git clone failed log [Setup Log 2024-11-26 #002.txt](https://github.com/user-attachments/files/17932252/Setup.Log.2024-11-26.002.txt)
---
Before submitting a Pull Request, please ensure the following:
=> fix(jihulab): redirect the submodules' URL from github to jihulab

src/InnoSetup/Environment.iss, src/InnoSetup/PostInstall.iss
Ensure consistency of the git repository state for both online and offline installers by extending the existing git reset logic.
Previously, `GitRepoFixFileMode` and `GitResetHard` (with the defined `GitUpdateSubmodules` function never used) were only invoked when the IDF was downloaded/cloned (online installer).
This change ensures that the same reset and submodule update steps are also executed when the IDF is unzipped from an archive (offline installer).
- Activated the existing `GitUpdateSubmodules` function (previously defined but unused).
- Moved invocation of `GitRepoFixFileMode`, `GitResetHard`, and `GitUpdateSubmodules` to be common for both install options.
- Verified with locally built online and offline installers for v5.4.1.
- After install, idf.py --version did not report a …
=> Update: Apply git reset and submodule update for both online and offline installers
